# -*- coding: utf-8 -*-
from django.test import SimpleTestCase,override_settings
from autoroute import Inspector
from django.core.urlresolvers import resolve
from app import views

class DefaultTestCase(SimpleTestCase):
    ''' Test cases for autoroute with default params. '''

    def test_auto_generated(self):
        resolver = resolve('/app/views/auto-generated/')
        self.assertEqual(resolver.func,views.auto_generated)

    def test_with_name(self):
        resolver = resolve('/app/views/with-name/')
        self.assertEqual(resolver.func,views.with_name)
        self.assertEqual(resolver.url_name,'with-name')

    def test_custom(self):
        resolver = resolve('/app/views/custom/')
        self.assertEqual(resolver.func,views.custom_route)
        self.assertEqual(resolver.url_name,'custom-name')


@override_settings(ROOT_URLCONF='camel_urls')
class CamelTestCase(SimpleTestCase):
    ''' Test cases for autoroute of `camel` style. '''

    def test_auto_generated(self):
        resolver = resolve('/app/views/autoGenerated/')
        self.assertEqual(resolver.func,views.auto_generated)

    def test_with_name(self):
        resolver = resolve('/app/views/withName/')
        self.assertEqual(resolver.func,views.with_name)
        self.assertEqual(resolver.url_name,'with-name')

    def test_custom(self):
        resolver = resolve('/app/views/custom/')
        self.assertEqual(resolver.func,views.custom_route)
        self.assertEqual(resolver.url_name,'custom-name')


@override_settings(ROOT_URLCONF='underscore_urls')
class UnderscoreTestCase(SimpleTestCase):
    ''' Test cases for autoroute of `underscore` style. '''

    def test_auto_generated(self):
        resolver = resolve('/app/views/auto_generated/')
        self.assertEqual(resolver.func,views.auto_generated)

    def test_with_name(self):
        resolver = resolve('/app/views/with_name/')
        self.assertEqual(resolver.func,views.with_name)
        self.assertEqual(resolver.url_name,'with-name')

    def test_custom(self):
        resolver = resolve('/app/views/custom/')
        self.assertEqual(resolver.func,views.custom_route)
        self.assertEqual(resolver.url_name,'custom-name')
